### ISSUE TITLE
Make page responsive

### ISSUE THREAD

**Issue by oorjitchowdhary** [oorjitchowdhary/recherche#1]
Currently the layout on smaller screens looks like this

![image](https://user-images.githubusercontent.com/39333058/65835127-00891600-e300-11e9-92bc-9074e5fdfafd.png)

### Deliverables
* `vertically center` the card
* `wrap` the title text
* keep the input box inside the card

**Comment by rachittt** [comment]
@oorjitchowdhary hey, I would like to work on this issue

**Comment by oorjitchowdhary** [comment]
@rachittt make a PR by Oct for getting it counted in hacktoberfest 😄
